# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 03:47
from __future__ import unicode_literals

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_auto_20180306_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.PublishComment', verbose_name='\u5f15\u7528')),
            ],
            options={
                'verbose_name': '\u8bdd\u9898\u8bc4\u8bba',
                'verbose_name_plural': '\u8bdd\u9898\u8bc4\u8bba',
            },
        ),
        migrations.AlterField(
            model_name='publish',
            name='pic1',
            field=models.ImageField(blank=True, help_text='\u8bdd\u9898\u914d\u56fe 300*300', null=True, upload_to=community.models.publish_img_path, verbose_name='\u8bdd\u9898\u914d\u56fe1'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='pic2',
            field=models.ImageField(blank=True, help_text='\u8bdd\u9898\u914d\u56fe 300*300', null=True, upload_to=community.models.publish_img_path, verbose_name='\u8bdd\u9898\u914d\u56fe2'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='pic3',
            field=models.ImageField(blank=True, help_text='\u8bdd\u9898\u914d\u56fe 300*300', null=True, upload_to=community.models.publish_img_path, verbose_name='\u8bdd\u9898\u914d\u56fe3'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='pic4',
            field=models.ImageField(blank=True, help_text='\u8bdd\u9898\u914d\u56fe 300*300', null=True, upload_to=community.models.publish_img_path, verbose_name='\u8bdd\u9898\u914d\u56fe4'),
        ),
        migrations.AddField(
            model_name='publishcomment',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Publish', verbose_name='\u8bdd\u9898'),
        ),
        migrations.AddField(
            model_name='publishcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
