# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20180306_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u6807\u9898\u540d\u79f0')),
                ('status', models.CharField(choices=[(b'1', '\u8349\u7a3f'), (b'2', '\u751f\u6548')], default=b'1', max_length=1, verbose_name='\u72b6\u6001')),
                ('order', models.PositiveIntegerField(default=100, help_text='\u4ece\u5c0f\u5230\u5927\u663e\u793a,\u76f8\u540c\u987a\u5e8f\u6309\u7167[\u663e\u793a\u53d1\u5e03\u65f6\u95f4]\u6392\u5e8f', verbose_name='\u6392\u5e8f')),
            ],
            options={
                'verbose_name': '\u8bdd\u9898\u7c7b\u578b',
                'verbose_name_plural': '\u8bdd\u9898\u7c7b\u578b',
            },
        ),
    ]
