# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-06 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_publishtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishcomment',
            options={'ordering': ['-create_time'], 'verbose_name': '\u8bdd\u9898\u8bc4\u8bba', 'verbose_name_plural': '\u8bdd\u9898\u8bc4\u8bba'},
        ),
        migrations.AddField(
            model_name='publish',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.PublishType', verbose_name='\u8bdd\u9898\u7c7b\u578b'),
        ),
    ]
