# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 03:11
from __future__ import unicode_literals

import community.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20180306_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=community.models.publish_img_path, verbose_name='\u8bdd\u9898\u56fe\u7247')),
                ('publish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Publish', verbose_name='\u8bdd\u9898')),
            ],
            options={
                'verbose_name': '\u8bdd\u9898\u56fe\u7247',
                'verbose_name_plural': '\u8bdd\u9898\u56fe\u7247',
            },
        ),
    ]
