# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_publishimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publish',
            name='status',
            field=models.CharField(choices=[(b'1', '\u8349\u7a3f'), (b'2', '\u751f\u6548')], default=b'2', max_length=1, verbose_name='\u72b6\u6001'),
        ),
    ]
