# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrauth',
            name='openid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='\u5fae\u4fe1openid'),
        ),
    ]
