# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-04 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrauth', '0004_auto_20180303_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='\u5ba2\u6237\u59d3\u540d')),
                ('mobile', models.CharField(max_length=128, verbose_name='\u7535\u8bdd')),
                ('info', models.TextField(verbose_name='\u5ba2\u6237\u610f\u5411')),
            ],
            options={
                'verbose_name': '\u88c5\u4fee\u9884\u7ea6',
                'verbose_name_plural': '\u88c5\u4fee\u9884\u7ea6',
            },
        ),
    ]
