# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-18 23:22
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import vrmode.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u6807\u9898')),
                ('intro', models.CharField(max_length=200, verbose_name='\u6458\u8981')),
                ('thumb', models.ImageField(help_text='\u5efa\u8bae\u5927\u5c0f\u4e3a815*400', upload_to=vrmode.models.page_img_path, verbose_name='\u5c01\u9762')),
                ('slug', models.SlugField(max_length=254, unique=True, verbose_name='\u552f\u4e00\u8def\u5f84')),
                ('status', models.CharField(choices=[(b'1', '\u8349\u7a3f'), (b'2', '\u751f\u6548')], default=b'1', max_length=1, verbose_name='\u72b6\u6001')),
                ('order', models.PositiveIntegerField(default=100, help_text='\u4ece\u5c0f\u5230\u5927\u663e\u793a,\u76f8\u540c\u987a\u5e8f\u6309\u7167[\u663e\u793a\u53d1\u5e03\u65f6\u95f4]\u6392\u5e8f', verbose_name='\u6392\u5e8f')),
                ('time_display', models.DateTimeField(verbose_name='\u663e\u793a\u53d1\u5e03\u65f6\u95f4')),
                ('content', DjangoUeditor.models.UEditorField(default=b'', verbose_name='\u5185\u5bb9')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='\u6700\u8fd1\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'page_static',
                'verbose_name': '\u9875\u9762\u53d1\u5e03',
                'verbose_name_plural': '\u9875\u9762\u53d1\u5e03',
            },
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u6807\u9898\u540d\u79f0')),
                ('status', models.CharField(choices=[(b'1', '\u8349\u7a3f'), (b'2', '\u751f\u6548')], default=b'1', max_length=1, verbose_name='\u72b6\u6001')),
                ('order', models.PositiveIntegerField(default=100, help_text='\u4ece\u5c0f\u5230\u5927\u663e\u793a,\u76f8\u540c\u987a\u5e8f\u6309\u7167[\u663e\u793a\u53d1\u5e03\u65f6\u95f4]\u6392\u5e8f', verbose_name='\u6392\u5e8f')),
            ],
            options={
                'db_table': 'page_type',
                'verbose_name': '\u9875\u9762\u7c7b\u578b',
                'verbose_name_plural': '\u9875\u9762\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='VRBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u6807\u9898')),
                ('intro', models.CharField(max_length=200, verbose_name='\u7b80\u4ecb')),
                ('cover', models.ImageField(help_text='\u8f6e\u64ad\u56fe\u7247 640*320', upload_to=vrmode.models.vrbanner_img_path, verbose_name='\u5c01\u9762')),
                ('vrlink', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u6587\u7ae0\u94fe\u63a5')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '\u9996\u9875\u8f6e\u64ad',
                'verbose_name_plural': '\u9996\u9875\u8f6e\u64ad',
            },
        ),
        migrations.CreateModel(
            name='VRMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u6807\u9898')),
                ('intro', models.CharField(max_length=200, verbose_name='\u7b80\u4ecb')),
                ('cover', models.ImageField(help_text='3D\u65b9\u6848\u5c01\u9762\u56fe\u7247 815*400', upload_to=vrmode.models.vrmode_img_path, verbose_name='\u5c01\u9762')),
                ('vrzip', models.FileField(blank=True, help_text='\u5982\u679c\u4fdd\u6301\u4e3a\u7a7a\uff0c\u8868\u793a\u53ea\u6709\u5c01\u9762\uff0c\u5426\u5219\u4e0a\u9762\u8bf7\u4e0a\u4f20vr\u538b\u7f29\u5305', null=True, upload_to=vrmode.models.vr_zip_path, verbose_name='vr\u6587\u4ef6\u538b\u7f29\u5305')),
                ('vrlink', models.CharField(blank=True, max_length=128, null=True, verbose_name='vr\u94fe\u63a5')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '3D\u65b9\u6848',
                'verbose_name_plural': '3D\u65b9\u6848',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='vrmode.PageType', verbose_name='\u9875\u9762\u7c7b\u578b'),
        ),
    ]
