# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrmode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='view_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='zan_times',
            field=models.IntegerField(default=0),
        ),
    ]
