# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrmode', '0002_auto_20180223_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, verbose_name='\u7528\u6237openid')),
                ('name', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('text', models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrmode.Page', verbose_name='\u9875\u9762')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vrmode.PageComment', verbose_name='\u5f15\u7528')),
            ],
            options={
                'db_table': 'page_comment',
                'verbose_name': '\u9875\u9762\u8bc4\u8bba',
                'verbose_name_plural': '\u9875\u9762\u8bc4\u8bba',
            },
        ),
    ]
