# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-27 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vrmode', '0003_pagecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagecomment',
            old_name='article',
            new_name='page',
        ),
    ]
