# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vrmode', '0004_auto_20180227_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrbanner',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vrmode.Page', verbose_name='\u9875\u9762'),
        ),
    ]
