# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-04 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrmode', '0006_auto_20180303_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrmode',
            name='tag1',
            field=models.CharField(default=b'14', max_length=100, verbose_name='\u6807\u8bb0\u4e00'),
        ),
        migrations.AddField(
            model_name='vrmode',
            name='tag2',
            field=models.CharField(default=b'MAR', max_length=100, verbose_name='\u6807\u8bb0\u4e8c'),
        ),
    ]
