# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-03 03:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vrmode', '0005_vrbanner_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='\u6700\u8fd1\u66f4\u65b0\u65f6\u95f4')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrmode.Page', verbose_name='\u9875\u9762')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'favorite_page',
                'verbose_name': '\u9875\u9762\u6536\u85cf',
                'verbose_name_plural': '\u9875\u9762\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='FavoriteVRMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='\u6700\u8fd1\u66f4\u65b0\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
                ('vrmode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vrmode.VRMode', verbose_name='VR\u573a\u666f')),
            ],
            options={
                'db_table': 'favorite_vrmode',
                'verbose_name': 'VR\u6536\u85cf',
                'verbose_name_plural': 'VR\u6536\u85cf',
            },
        ),
    ]
